SELECT USER_ID AS BUYER_ID, JOIN_DATE, ISNULL(COUNT(BUYER_ID),0) AS ORDERS_IN_2019
FROM USERS U
LEFT JOIN ORDERS O
ON U.USER_ID = O.BUYER_ID
AND YEAR(O.ORDER_DATE) = '2019'
GROUP BY USER_ID, JOIN_DATE
