WITH CTE_ORDER AS (
SELECT LOG_ID, ROW_NUMBER() OVER (ORDER BY LOG_ID) AS RN
FROM LOGS),
CTE_DIFF AS (
SELECT LOG_ID, (LOG_ID - RN) AS DIFF
FROM CTE_ORDER)
SELECT MIN(LOG_ID) AS START_ID, MAX(LOG_ID) AS END_ID
FROM CTE_DIFF
GROUP BY DIFF
