-- Pending Solution
-- **Recursive CTE Usecase**
WITH CTE_MAX_ID AS
(SELECT MAX(CUSTOMER_ID) AS MAX_ID
 FROM CUSTOMERS),
CTE_REMAINING AS
(SELECT DISTINCT CUSTOMER_ID
 FROM CUSTOMERS, CTE_MAX_ID
 WHERE CUSTOMER_ID != MAX_ID)
 SELECT * FROM CTE_REMAINING
 
