-- APPROACH 1: DENSE_RANK() WITH PARTITION BY DEPARTMENT ORDER BY SALARY
WITH CTE_RANK_DEPARTMENT AS 
(SELECT DEPARTMENTID, NAME, SALARY, DENSE_RANK() OVER (PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS RN
 FROM EMPLOYEE)
 SELECT D.NAME AS DEPARTMENT, CTE.NAME AS EMPLOYEE, CTE.SALARY
 FROM CTE_RANK_DEPARTMENT CTE
 JOIN DEPARTMENT D
 ON CTE.DEPARTMENTID = D.ID
 WHERE CTE.RN = 1
 
 -- APPROACH 2: FIND DEPARTMENTS MAX SALARY USING GROUP BY AND FIND EMPLOYEE WITH THOSE SALARIES USING TEMP TABLE
SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON E.DEPARTMENTID = D.ID
JOIN (SELECT DEPARTMENTID, MAX(SALARY) AS SALARY
      FROM   EMPLOYEE
      GROUP BY DEPARTMENTID) TEMP
ON E.SALARY = TEMP.SALARY AND E.DEPARTMENTID = TEMP.DEPARTMENTID

