-- APPROACH 1: DENSE_RANK() WITH PARTITION BY DEPARTMENT ORDER BY SALARY
WITH CTE_RANK_DEPARTMENT AS 
(SELECT DEPARTMENTID, NAME, SALARY, DENSE_RANK() OVER (PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS RN
 FROM EMPLOYEE)
 SELECT D.NAME AS DEPARTMENT, CTE.NAME AS EMPLOYEE, CTE.SALARY
 FROM CTE_RANK_DEPARTMENT CTE
 JOIN DEPARTMENT D
 ON CTE.DEPARTMENTID = D.ID
 WHERE CTE.RN = 1
