-- TO COUNT THE NUMBER OF MATCHES PLAYED BY EVERY TEAM
WITH CTE_MATCHES AS 
    ( 
      SELECT HOME_TEAM_ID AS TEAM FROM MATCHES
      UNION ALL
      SELECT AWAY_TEAM_ID AS TEAM FROM MATCHES
    ),
-- TO FIND OUT THE WINS/LOSSES FOR A TEAM
CTE_RESULTS AS 
    (
    SELECT HOME_TEAM_ID, AWAY_TEAM_ID,
        CASE 
            WHEN HOME_TEAM_GOALS > AWAY_TEAM_GOALS THEN HOME_TEAM_ID
            WHEN HOME_TEAM_GOALS < AWAY_TEAM_GOALS THEN AWAY_TEAM_ID
            WHEN HOME_TEAM_GOALS = AWAY_TEAM_GOALS THEN 0
        END AS RESULT
    FROM MATCHES
    )
,
-- CALCULATE POINTS FOR A TEAM
CTE_POINTS AS 
    (
    SELECT TEAM_ID, 
        ISNULL((SUM (CASE
            WHEN RESULT = TEAM_ID THEN 3
            WHEN RESULT = TEAM_ID THEN 3
            WHEN RESULT = 0 THEN 1
        END)),0) AS POINTS
    FROM CTE_RESULTS
    JOIN TEAMS
    ON CTE_RESULTS.HOME_TEAM_ID = TEAMS.TEAM_ID OR CTE_RESULTS.AWAY_TEAM_ID = TEAMS.TEAM_ID
    GROUP BY TEAM_ID
    )
,
-- CALCULATE GOALS FOR
CTE_GOALS_FOR AS 
    (SELECT TEAM, SUM(GOALS_FOR) AS GOAL_FOR FROM
    (
    SELECT HOME_TEAM_ID AS TEAM, HOME_TEAM_GOALS AS GOALS_FOR FROM MATCHES
    UNION ALL
    SELECT AWAY_TEAM_ID AS TEAM, AWAY_TEAM_GOALS AS GOALS_FOR FROM MATCHES
    ) A
    GROUP BY TEAM)
    ,
-- CALCULATE GOALS AGAINST
CTE_GOALS_AGAINST AS 
    (SELECT TEAM, SUM(GOALS_AGAINST) AS GOAL_AGAINST FROM
    (
    SELECT HOME_TEAM_ID AS TEAM, AWAY_TEAM_GOALS AS GOALS_AGAINST FROM MATCHES
    UNION ALL
    SELECT AWAY_TEAM_ID AS TEAM, HOME_TEAM_GOALS AS GOALS_AGAINST FROM MATCHES
    )A
    GROUP BY TEAM)
SELECT DISTINCT team_name, matches_played, points, goal_for, goal_against, (goal_for - goal_against) AS goal_diff
FROM (
    (
        SELECT TEAM AS ID, COUNT(*) AS MATCHES_PLAYED
        FROM CTE_MATCHES
        GROUP BY TEAM
    ) A
LEFT JOIN
    (
        SELECT TEAM_ID, POINTS
        FROM CTE_POINTS
    ) B
ON A.ID = B.TEAM_ID
LEFT JOIN
    (
        SELECT TEAM,GOAL_FOR
        FROM CTE_GOALS_FOR
    ) C
ON A.ID =  C.TEAM
LEFT JOIN
    (
        SELECT TEAM,GOAL_AGAINST
        FROM CTE_GOALS_AGAINST
    ) D
ON A.ID = D.TEAM
LEFT JOIN 
    (
        SELECT TEAM_ID,TEAM_NAME
        FROM TEAMS
    ) E
ON A.ID = E.TEAM_ID
) 
ORDER BY POINTS DESC, GOAL_DIFF DESC, TEAM_NAME asc 
