-- RANKING SALARIES BY DEPARTMENT
-- WE USE DENSE RANK TO RETAIN THE ORDER OF THE RANKS WHEN THERE ARE DUPLICATE SALARIES FOR MULTIPLE EMPLOYEES
WITH CTE_RANK_SALARY AS 
(SELECT NAME, DEPARTMENTID, SALARY, DENSE_RANK() OVER (PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) RN
 FROM EMPLOYEE)
 -- SELECTING CUSTOMERS WITH RANK <= 3 BY DEPARTMENT
 SELECT D.NAME AS DEPARTMENT, CTE.NAME AS EMPLOYEE, CTE.SALARY
 FROM CTE_RANK_SALARY CTE
 JOIN DEPARTMENT D
 ON CTE.DEPARTMENTID = D.ID
 WHERE RN <=3
