WITH CTE_COUNT_FOLLOWERS AS
(SELECT R1.USER_ID, R2.USER_ID AS USER_ID2, COUNT(DISTINCT R1.FOLLOWER_ID) AS COUNT
 FROM RELATIONS R1
 JOIN RELATIONS R2
 ON R1.FOLLOWER_ID = R2.FOLLOWER_ID AND R1.USER_ID <> R2.USER_ID AND R1.USER_ID < R2.USER_ID
 GROUP BY R1.USER_ID, R2.USER_ID)
 SELECT USER_ID AS USER1_ID, USER_ID2 AS USER2_ID
 FROM CTE_COUNT_FOLLOWERS
 WHERE COUNT = (SELECT MAX(COUNT) FROM CTE_COUNT_FOLLOWERS)
