/* Write your T-SQL query statement below */
-- Min Requirements Condition by School
-- CAPACITY >= STUDENT_COUNT I.E MIN(DIFF) WHERE DIFF = CAPACITY - STUDENT_COUNT
-- RETURN SCHOOL_ID AND SCORE BY STUDENT_COUNT
WITH CTE_DIFF AS
(SELECT SCHOOL_ID, STUDENT_COUNT, SCORE, (CAPACITY - STUDENT_COUNT) AS DIFF
 FROM SCHOOLS, EXAM
 WHERE CAPACITY >= STUDENT_COUNT),
 CTE_RANK_DIFF AS
 (SELECT SCHOOL_ID, SCORE, ROW_NUMBER() OVER (PARTITION BY SCHOOL_ID ORDER BY DIFF, SCORE ASC) RN
  FROM CTE_DIFF)
 SELECT S.SCHOOL_ID, ISNULL(SCORE,-1) AS SCORE
 FROM SCHOOLS S
 LEFT JOIN (SELECT * FROM CTE_RANK_DIFF WHERE RN = 1) CTE
 ON S.SCHOOL_ID = CTE.SCHOOL_ID
