-- CREATE UPPER AND LOWER BOUND FOR INTERVAL TYPE PROBLEMS
WITH bus_bounds AS (
  SELECT
    B.bus_id,
    LAG(B.arrival_time, 1, -1) OVER (ORDER BY B.arrival_time) lower_bound,
    B.arrival_time AS upper_bound
  FROM
    Buses B
)
SELECT BUS_ID, COUNT(PASSENGER_ID) AS PASSENGERS_CNT
FROM BUS_BOUNDS B
LEFT JOIN PASSENGERS P
ON P.ARRIVAL_TIME > LOWER_BOUND AND P.ARRIVAL_TIME <= UPPER_BOUND
GROUP BY BUS_ID
