WITH CTE_CURR_GLOBAL_RANK AS
(SELECT TEAM_ID, NAME, POINTS, DENSE_RANK() OVER (ORDER BY POINTS DESC, NAME ASC) AS RN
 FROM TEAMPOINTS),
 CTE_UPDATE_POINTS AS
(SELECT TP.TEAM_ID, TP.NAME, SUM(POINTS + ISNULL(POINTS_CHANGE,0)) AS NEW_POINTS
 FROM TEAMPOINTS TP
 LEFT JOIN POINTSCHANGE PC
 ON TP.TEAM_ID = PC.TEAM_ID
 GROUP BY TP.TEAM_ID, TP.NAME),
 CTE_UPDATE_GLOBAL_RANK AS
 (SELECT CTE1.TEAM_ID, NAME,
  DENSE_RANK() OVER (ORDER BY NEW_POINTS DESC, NAME ASC) AS RN_NEW,
  RN
  FROM CTE_UPDATE_POINTS CTE1
  JOIN (SELECT TEAM_ID, RN FROM CTE_CURR_GLOBAL_RANK) CTE2
  ON CTE1.TEAM_ID = CTE2.TEAM_ID)
  SELECT TEAM_ID, NAME, (RN - RN_NEW) AS RANK_DIFF
  FROM CTE_UPDATE_GLOBAL_RANK
  
