-- APPROACH 1
-- CANCELLATION RATE: NUMBER OF CANCELED REQUESTS BY UNBANNED USERS / TOTAL NUMBER OF UNBANNED REQUESTS BY DAY
-- BOTH CLIENT AND DRIVER ID MUST NOT BE BANNED
-- BETWEEN '2013-10-01' AND '2013-10-03'

-- DAILY CANCELED UNBANNED REQUESTS BY DAY
WITH CTE_DAILY_CANCELED_REQUESTS AS 
(SELECT REQUEST_AT AS DAY, COUNT(CLIENT_ID) AS CANCELED_COUNT
 FROM TRIPS
 WHERE STATUS LIKE 'CANCELLED_%' AND
 CLIENT_ID NOT IN (SELECT USERS_ID FROM USERS WHERE BANNED = 'YES') AND
 DRIVER_ID NOT IN (SELECT USERS_ID FROM USERS WHERE BANNED = 'YES') AND
 REQUEST_AT BETWEEN '2013-10-01' AND '2013-10-03'
 GROUP BY REQUEST_AT),
-- TOTAL UNBANNED REQUESTS BY DAY
CTE_TOTAL_REQUESTS AS 
(SELECT REQUEST_AT AS DAY, COUNT(CLIENT_ID) AS TOTAL_REQUESTS
 FROM TRIPS
 WHERE CLIENT_ID NOT IN (SELECT USERS_ID FROM USERS WHERE BANNED = 'YES') AND
 DRIVER_ID NOT IN (SELECT USERS_ID FROM USERS WHERE BANNED = 'YES') AND
 REQUEST_AT BETWEEN '2013-10-01' AND '2013-10-03'
 GROUP BY REQUEST_AT)
-- CANCELLATION RATE BY DAY
 SELECT CTE2.DAY, ISNULL(ROUND((CTE1.CANCELED_COUNT * 1.0) / CTE2.TOTAL_REQUESTS, 2),0) AS [CANCELLATION RATE]
 FROM CTE_DAILY_CANCELED_REQUESTS CTE1
 FULL JOIN CTE_TOTAL_REQUESTS CTE2
 ON CTE1.DAY = CTE2.DAY
