/* Write your T-SQL query statement below */
WITH CTE_SORT AS 
(SELECT ID, COMPANY, SALARY, RANK() OVER (PARTITION BY COMPANY ORDER BY SALARY,ID ASC) AS RN
FROM EMPLOYEE),
CTE_MID_RN AS
(SELECT ID,COMPANY, MAX(RN) OVER (PARTITION BY COMPANY) AS MAX_RN
 FROM CTE_SORT),
CTE_MID AS 
(SELECT COMPANY, COUNT(ID) AS CNT, (COUNT(ID)/2) + 1 AS MID
 FROM EMPLOYEE
 GROUP BY COMPANY
 UNION ALL
 -- COVERING THE EVEN COUNT EDGE CASE
 SELECT COMPANY, COUNT(ID) AS CNT, (COUNT(ID)/2) AS MID
 FROM EMPLOYEE
 GROUP BY COMPANY
 HAVING COUNT(ID) % 2 = 0 
 )
 SELECT C.ID, C.COMPANY, C.SALARY FROM (
  (SELECT * FROM CTE_SORT)  C
  JOIN (SELECT COMPANY, MID FROM CTE_MID) B
  ON C.COMPANY = B.COMPANY AND C.RN = B.MID) 
  
