WITH CTE_COUNT_FOLLOWERS AS
(SELECT FOLLOWEE, COUNT(FOLLOWEE) AS FOLL0WERS
 FROM FOLLOW
 GROUP BY FOLLOWEE
 HAVING COUNT(FOLLOWEE) >= 1)
-- COUNT OF FOLLOWERS HAVING ATLEAST ONE FOLLOWER
 SELECT DISTINCT FOLLOWER , FOLL0WERS AS NUM
 FROM FOLLOW
 JOIN CTE_COUNT_FOLLOWERS
 ON FOLLOW.FOLLOWER = CTE_COUNT_FOLLOWERS.FOLLOWEE
